`default_nettype none

// KR260 true synthesis top-level.
// Connects the PS block design (ps_bd_wrapper) to the SoC wrapper.
//
// ps_bd_wrapper is generated by Vivado from fpga/create_project_kr260.tcl.
// It exposes:
//   pl_clk0_0    — FCLK0, configured for 100 MHz
//   pl_resetn0_0 — active-low PL reset, de-asserts after PS boot

module kr260_top (
    output wire [7:0] rpi_gpio
);

wire clk, rst_n;

ps_bd_wrapper ps_bd_i (
    .pl_clk0_0    (clk),
    .pl_resetn0_0 (rst_n)
);

fpga_top_kr260 soc_top (
    .clk      (clk),
    .rst_n    (rst_n),
    .rpi_gpio (rpi_gpio)
);

endmodule
